docs/ABOUT.md
It has the advantage of not needing to figure out how to properly escape `)` in markdown ;-)
=> fix dlang link to dlang.org

config.json
I updated the `configlet` tool which lints Exercism tracks so that it uses the "exercises" rather than the (now deprecated) "problems" key.
=> Add missing slug to exercises key in config

.travis.yml, README.md, bin/test-all-exercises, bin/test-exercise, exercises/difference-of-squares/difference_of_squares.d, exercises/difference-of-squares/difference_of_squares_example.d, exercises/gigasecond/gigasecond.d, exercises/gigasecond/gigasecond_example.d, exercises/hello-world/hello_world.d, exercises/hello-world/hello_world_example.d, exercises/raindrops/raindrops.d, exercises/raindrops/raindrops_example.d, exercises/rna-transcription/rna_transcription.d, exercises/rna-transcription/rna_transcription_example.d
this helps us ensure that our tests are solvable
To be able to achieve this, `main` had to be added to some exercises, as it would not compile without.
In consideration of #30 being a very large proposal, the Travis portion of that proposal has been extracted out into its own PR, so that it can be evaluated and merged separately.
Note that this PR necessarily differs in how it runs its tests, since it uses `dmd` instead of `dub test`, and it does require a `main` for each `.d` file (`dub test` does not). This can help contrast it with #30.
If this is merged before #30, I will have to rebase #30; I am prepared to do that.
=> travis: test all exercises 

exercises/nucleotide-count/nucleotide_count.d
Hello,
I'm currently going through exercism D exercices and today I made the nucleotide_count one.
I noticed there was something wrong with the unit test. The aaEqual function requires ulong[char] parameters whereas the already written given test sends a int[char]. So as we know int can sometimes be passed as ulong but ulong can't be passed as an int. So I first checked other people answers and everyone had to mess around with the unit test to make it work. So I just changed the aaEqual parameters type to ulong instead of int so everything works.
Best regards.
=> fixed type issue

exercises/circular-buffer/example/circular_buffer.d, exercises/circular-buffer/source/circular_buffer.d, exercises/etl/example/etl.d, exercises/hamming/example/hamming.d, exercises/hamming/source/hamming.d, exercises/nucleotide-count/example/nucleotide_count.d, exercises/nucleotide-count/source/nucleotide_count.d, exercises/rna-transcription/example/rna_transcription.d, exercises/rna-transcription/source/rna_transcription.d, exercises/series/example/series.d, exercises/series/source/series.d, exercises/triangle/example/triangle.d, exercises/triangle/source/triangle.d
The D style guide at https://dlang.org/dstyle.html says to prefer local
selective imports.
The indentation is inconsistent here, but I'm not sure there is much I
can do without making the files look inconsistent. I took the rule of
"use indentation level of next line".
=> use specific imports of assertThrown, adding them where missing

config/exercise_readme.go.tmpl, exercises/bob/README.md, exercises/circular-buffer/README.md, exercises/crypto-square/README.md, exercises/difference-of-squares/README.md, exercises/etl/README.md, exercises/gigasecond/README.md, exercises/hamming/README.md, exercises/hello-world/README.md, exercises/leap/README.md, exercises/nucleotide-count/README.md, exercises/pangram/README.md, exercises/raindrops/README.md, exercises/react/README.md, exercises/rna-transcription/README.md, exercises/robot-name/README.md, exercises/roman-numerals/README.md, exercises/series/README.md, exercises/triangle/README.md
We are working towards making exercises stand-alone. That is to say: no more generating READMEs on the fly.
This will give maintainers more control over each individual exercise README, and it will also make some of the backend logic for delivering exercises simpler.
The README template uses the Go text/template package, and the default templates generate the same READMEs as we have been generating on the fly.  See the documentation in [regenerating exercise readmes][regenerate-docs] for details.
The READMEs can be generated at any time using a new 'generate' command in configlet. This command has not yet landed in master or been released, but can be built from source in the generate-readmes branch on [configlet][].
[configlet]: https://github.com/exercism/configlet
[regenerate-docs]: …
=> Generate static exercise README templates

exercises/crypto-square/.dub/dub.json, exercises/crypto-square/example/crypto_square.d
Fixes #49.
The build failed because of the deprecation warnings. They aren't a big deal unless `
buildRequirements "disallowDeprecations"` is specified in the `dub.sdl` and this is exactly what happened.
I don't know why such option is in `dub.sdl`, because a lot of stuff in the D's standard library get deprecated and builds will continue failing for "no reason".
=> Fix Travis CI builds

README.md
This is so that we don't have to leave #3 open. We can do this in response to real-world use cases.
=> Tweak contributing section of README

config.json, exercises/rna-transcription/example/rna_transcription.d, exercises/run-length-encoding/README.md, exercises/run-length-encoding/dub.sdl, exercises/run-length-encoding/example/run_length_encoding.d, exercises/run-length-encoding/source/run_length_encoding.d
Hi, this PR is to add the `run-length-encoding` exercise based off the [problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/run-length-encoding).
There is also a fix for the build due to an issue for deprecation warning in D v2.087.0
Thanks!
=> Adds run-length-encoding exercise

config.json, exercises/resistor-color/README.md, exercises/resistor-color/dub.sdl, exercises/resistor-color/example/resistor_color.d, exercises/resistor-color/source/resistor_color.d
Hi, this PR is to add the `resistor-color` exercise based off the [problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/resistor-color).
Thanks!
=> Adds resistor-color exercise

config.json, exercises/resistor-color-duo/README.md, exercises/resistor-color-duo/dub.sdl, exercises/resistor-color-duo/example/resistor_color_duo.d, exercises/resistor-color-duo/source/resistor_color_duo.d
Hi, this PR is to add the `resistor-color-duo` exercise based off the [problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/resistor-color-duo).
Thanks!
=> Adds resistor-color-duo exercise

config.json
~~Closes #137~~
Closes #118 
Closes #117 
Filled the tags out to the best of my ability. If I'm missing anything, let me know and I'll get it added!
=> Add slug and tags to config.json

.github/workflows/tests.yml
configlet lint already runs as part of the `configlet` workflow, so running it a second time was unneeded
=> ci: remove duplicate linting action

config.json, exercises/practice/scrabble-score/.docs/instructions.md, exercises/practice/scrabble-score/.meta/config.json, exercises/practice/scrabble-score/.meta/tests.toml, exercises/practice/scrabble-score/dub.sdl, exercises/practice/scrabble-score/example/scrabble_score.d, exercises/practice/scrabble-score/source/scrabble_score.d
=> Add scrabble-score

exercises/practice/resistor-color-duo/.meta/tests.toml, exercises/practice/resistor-color-duo/source/resistor_color_duo.d
Added two missing tests and a stubbed class definition for students.
=> Update resistor-color-duo tests

exercises/practice/triangle/.meta/tests.toml, exercises/practice/triangle/example/triangle.d, exercises/practice/triangle/source/triangle.d
I noticed two tests were missing according to configlet sync, but in fact several tests were not present. Due to the exercise setup, I couldn't implement "equilateral triangles are also isosceles" without breaking 23 community solutions so that was excluded. Finally, I added a stub for the kind function to the student's file.
=> Sync triangle tests

config.json, exercises/practice/acronym/.docs/instructions.md, exercises/practice/acronym/.meta/config.json, exercises/practice/acronym/.meta/tests.toml, exercises/practice/acronym/dub.sdl, exercises/practice/acronym/example/acronym.d, exercises/practice/acronym/source/acronym.d
For #48in24. I sourced the regexp from Bethany at http://forum.exercism.org/t/48in24-exercise-02-27-acronym/9806/12.
=> Add acronym

exercises/practice/pangram/source/pangram.d, exercises/practice/prime-factors/source/prime_factors.d
37 of the exercises use an int for allTestsEnabled, and that's what the test runner also expects when it enables all tests to be run.
=> Make allTestsEnabled typing consistent

exercises/practice/knapsack/source/knapsack.d
Our struct literals for the Items no longer specify field names. This avoids test compilation
errors when students submit solutions.
https://dlang.org/spec/struct.html#struct-literal
=> knapsack - struct literals

exercises/practice/circular-buffer/source/circular_buffer.d, exercises/practice/run-length-encoding/source/run_length_encoding.d, exercises/practice/sum-of-multiples/source/sum_of_multiples.d
=> exercise stubs - part 4 of 4

docs/TESTS.md
The first commit merely reformats the file according to [exercism markdown standard layout](https://exercism.org/docs/building/markdown/markdown#h-layout).
The second commit adds the new text.
=> Add secion to Tests document describing unittest output

exercises/practice/armstrong-numbers/.meta/tests.toml
=> Sync armstrong-numbers tests

exercises/practice/crypto-square/.meta/tests.toml, exercises/practice/crypto-square/source/crypto_square.d
=> sync crypto-square
