exercism/d

config.json

This adds the `exercise` key to `config.json`, with the expected properties. The values are currently left as simple placeholders.
The next phase will adjust the values for these properties.

Add new problem specifications - phase 1.

---

config.json

Add initial estimation of exercise difficulty - that comes from my experience solving the exercises.

Add difficulty for each exercise.

---

config.json

Add topics for the exercises. These are my initial "estimations" based on how I solved the exercises, but I think it should be an iterative process starting there.

Exercise topics

---

config.json

This is no longer referenced anywhere.

Delete deprecated key from config.json

---

config.json
exercises/leap/leap.d
exercises/leap/leap_example.d

Reviewers: Please note that this contains all commits from #31. This is because I am not willing to contribute an exercise without Travis proving that the example implementation I provide is correct. So either:
* #31 should be merged first, and then this PR
* or #30 should merged first and ask me to rebase this PR, which I will, then merge this PR

leap: add to track

---

config.json
exercises/react/react.d
exercises/react/react_example.d

Reviewers: Please note that this contains all commits from #31. This is because I am not willing to contribute an exercise without Travis proving that the example implementation I provide is correct. So either:
* #31 should be merged first, and then this PR
* or #30 should merged first and ask me to rebase this PR, which I will, then merge this PR

react: add to track

---

config.json

See the discussion https://github.com/exercism/discussions/issues/161

Rename the track for the sake of consistency

---

docs/EXERCISE_README_INSERT.md
exercises/bob/README.md
exercises/circular-buffer/README.md
exercises/crypto-square/README.md
exercises/difference-of-squares/README.md
exercises/etl/README.md
exercises/gigasecond/README.md
exercises/hamming/README.md
exercises/hello-world/README.md
exercises/leap/README.md
exercises/nucleotide-count/README.md
exercises/pangram/README.md
exercises/raindrops/README.md
exercises/react/README.md
exercises/rna-transcription/README.md
exercises/robot-name/README.md
exercises/roman-numerals/README.md
exercises/series/README.md
exercises/triangle/README.md

Correct README.md link to correct D page.

---

exercises/hello-world/example/hello_world.d
exercises/hello-world/source/hello_world.d

References [exercism/exercism#4707](https://github.com/exercism/exercism/issues/4707)

simplify hello world exercise, exercism#4707

---

.gitignore
config.json
exercises/reverse-string/README.md
exercises/reverse-string/dub.sdl
exercises/reverse-string/example/reverse_string.d
exercises/reverse-string/source/reverse_string.d

Hi, this PR is to add the `reverse-string` exercise based off the [problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/reverse-string).
Thanks!

Adds reverse-string exercise

---

exercises/pangram/source/pangram.d

Fixes a typo and changes style to camelCase

Fix typo in pangram exercises

---

exercises/etl/source/etl.d

All [names in D should be camelCased](https://dlang.org/dstyle.html#naming_general). This small pr just renames couple of variables to follow D's conventions.

Improve style if etl exercise

---

config.json
exercises/collatz-conjecture/README.md
exercises/collatz-conjecture/dub.sdl
exercises/collatz-conjecture/example/collatz_conjecture.d
exercises/collatz-conjecture/source/collatz_conjecture.d

Hi, this PR is to add the `collatz-conjecture` exercise based off the [problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/collatz-conjecture).
Thanks!

Adds collatz-conjecture exercise

---

config.json
exercises/armstrong-numbers/README.md
exercises/armstrong-numbers/dub.sdl
exercises/armstrong-numbers/example/armstrong_numbers.d
exercises/armstrong-numbers/source/armstrong_numbers.d

Hi, this PR is to add the `armstrong-numbers` exercise based off the [problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/armstrong-numbers).
Thanks!

Adds armstrong-numbers exercise

---

config.json
exercises/two-fer/README.md
exercises/two-fer/dub.sdl
exercises/two-fer/example/two_fer.d
exercises/two-fer/source/two_fer.d

Hi, this PR is to add the `two-fer` exercise based off the [problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/two-fer).
Thanks!

Adds two-fer exercise

---

config.json
exercises/isogram/README.md
exercises/isogram/dub.sdl
exercises/isogram/example/isogram.d
exercises/isogram/source/isogram.d

Hi, this PR is to add the `isogram` exercise based off the [problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/isogram).
Thanks!

Adds isogram exercise

---

config.json
exercises/darts/README.md
exercises/darts/dub.sdl
exercises/darts/example/darts.d
exercises/darts/source/darts.d

Hi, this PR is to add the `darts` exercise based off the [problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/darts).
Thanks!

Adds darts exercise

---

config.json
exercises/perfect-numbers/README.md
exercises/perfect-numbers/dub.sdl
exercises/perfect-numbers/example/perfect_numbers.d
exercises/perfect-numbers/source/perfect_numbers.d

Hi, this PR is to add the `perfect-numbers` exercise based off the [problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/perfect-numbers).
Thanks!

Adds perfect-numbers exercise

---

config.json
exercises/sum-of-multiples/README.md
exercises/sum-of-multiples/dub.sdl
exercises/sum-of-multiples/example/sum_of_multiples.d
exercises/sum-of-multiples/source/sum_of_multiples.d

Hi, this PR is to add the `sum-of-multiples` exercise based off the [problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/sum-of-multiples).
Thanks!

Adds sum-of-multiples exercise

---

config.json
exercises/prime-factors/README.md
exercises/prime-factors/dub.sdl
exercises/prime-factors/example/prime_factors.d
exercises/prime-factors/source/prime_factors.d

Hi, this PR is to add the `prime-factors` exercise based off the [problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/prime-factors).
Thanks!

Adds prime-factors exercise

---

config.json
exercises/luhn/README.md
exercises/luhn/dub.sdl
exercises/luhn/example/luhn.d
exercises/luhn/source/luhn.d

Hi, this PR is to add the `luhn` exercise based off the [problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/luhn).
Thanks!

Adds luhn exercise

---

config.json
exercises/nth-prime/README.md
exercises/nth-prime/dub.sdl
exercises/nth-prime/example/nth_prime.d
exercises/nth-prime/source/nth_prime.d

Hi, this PR is to add the `nth-prime` exercise based off the [problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/nth-prime).
Thanks!

Adds nth-prime exercise

---

config.json
exercises/matching-brackets/README.md
exercises/matching-brackets/dub.sdl
exercises/matching-brackets/example/matching_brackets.d
exercises/matching-brackets/source/matching_brackets.d

Hi, this PR is to add the `matching-brackets` exercise based off the [problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/matching-brackets).
Thanks!

Adds matching-brackets exercise

---

config.json
exercises/grains/README.md
exercises/grains/dub.sdl
exercises/grains/example/grains.d
exercises/grains/source/grains.d

Hi, this PR is to add the `grains` exercise based off the [problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/grains).
Thanks!

Adds grains exercise

---

bin/test-all-exercises

TODO: Doesn't handle concept exercises
(a v3 change)

test-all-exercises: Handle practice exercises

---

.github/workflows/tests.yml
.travis.yml
README.md

The Exercism organisation is moving to GitHub Actions.
It runs faster.
Closes https://github.com/exercism/d/issues/111

Move from Travis to GitHub Actions

---

exercises/practice/hello-world/source/hello_world.d

Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46

🤖 Simplify `hello-world` stub

---

exercises/practice/armstrong-numbers/.meta/config.json
exercises/practice/bob/.meta/config.json
exercises/practice/circular-buffer/.meta/config.json
exercises/practice/collatz-conjecture/.meta/config.json
exercises/practice/crypto-square/.meta/config.json
exercises/practice/darts/.meta/config.json
exercises/practice/difference-of-squares/.meta/config.json
exercises/practice/etl/.meta/config.json
exercises/practice/gigasecond/.meta/config.json
exercises/practice/grains/.meta/config.json
exercises/practice/hamming/.meta/config.json
exercises/practice/hello-world/.meta/config.json
exercises/practice/leap/.meta/config.json
exercises/practice/luhn/.meta/config.json
exercises/practice/nth-prime/.meta/config.json
exercises/practice/nucleotide-count/.meta/config.json
exercises/practice/perfect-numbers/.meta/config.json
exercises/practice/prime-factors/.meta/config.json
exercises/practice/resistor-color/.meta/config.json
exercises/practice/reverse-string/.meta/config.json
exercises/practice/rna-transcription/.meta/config.json
exercises/practice/roman-numerals/.meta/config.json
exercises/practice/series/.meta/config.json
exercises/practice/sum-of-multiples/.meta/config.json
exercises/practice/triangle/.meta/config.json
exercises/practice/two-fer/.meta/config.json

This brings in recent improvements to the metadata for all practice exercises.

Sync metadata with problem-specifications

---

exercises/practice/reverse-string/.approaches/bygrapheme-retro-bycodepoint-text/content.md
exercises/practice/reverse-string/.approaches/bygrapheme-retro-bycodepoint-text/snippet.txt
exercises/practice/reverse-string/.approaches/config.json
exercises/practice/reverse-string/.approaches/introduction.md

Unicode-aware approach for Reverse String.

Reverse String approach

---

exercises/practice/hamming/.approaches/config.json
exercises/practice/hamming/.approaches/introduction.md
exercises/practice/hamming/.approaches/zip-count/content.md
exercises/practice/hamming/.approaches/zip-count/snippet.txt

Hamming approach

---

exercises/practice/isogram/.approaches/config.json
exercises/practice/isogram/.approaches/filter-map-fold/content.md
exercises/practice/isogram/.approaches/filter-map-fold/snippet.txt
exercises/practice/isogram/.approaches/filter-map-foreach/content.md
exercises/practice/isogram/.approaches/filter-map-foreach/snippet.txt
exercises/practice/isogram/.approaches/introduction.md

Isogram approaches

---

config.json
exercises/practice/hamming/.approaches/config.json
exercises/practice/isogram/.approaches/config.json
exercises/practice/pangram/.approaches/config.json
exercises/practice/reverse-string/.approaches/config.json

@ErikSchierboom, a quick and easy format before I do some exercise ports

Format configs

---

docs/TESTS.md

@ErikSchierboom, this is a quick grammar fix I noticed. Feel free to mark this as rep/tiny.

Use past participle of run in TESTS.md

---

docs/INSTALLATION.md

@ErikSchierboom, I noticed some broken formatting on the installation directions so I took the opportunity to tweak the docs. If there's more cleanup to be done, let me know. :)

Minor cleanup of installation directions

---

config.json
exercises/practice/space-age/.docs/instructions.md
exercises/practice/space-age/.meta/config.json
exercises/practice/space-age/.meta/tests.toml
exercises/practice/space-age/dub.sdl
exercises/practice/space-age/example/space_age.d
exercises/practice/space-age/source/space_age.d

Related to #48in24. See #214 for tracking.

Add space-age

---

config.json
exercises/practice/eliuds-eggs/.docs/instructions.md
exercises/practice/eliuds-eggs/.docs/introduction.md
exercises/practice/eliuds-eggs/.meta/config.json
exercises/practice/eliuds-eggs/.meta/tests.toml
exercises/practice/eliuds-eggs/dub.sdl
exercises/practice/eliuds-eggs/example/eliuds_eggs.d
exercises/practice/eliuds-eggs/source/eliuds_eggs.d

For #48in24 and related to #214

Add eliud's eggs

---

config.json
exercises/practice/allergies/.docs/instructions.md
exercises/practice/allergies/.meta/config.json
exercises/practice/allergies/.meta/tests.toml
exercises/practice/allergies/dub.sdl
exercises/practice/allergies/example/allergies.d
exercises/practice/allergies/source/allergies.d

For #48in24 and related to #214

Add allergies

---

config.json
exercises/practice/dnd-character/.docs/instructions.md
exercises/practice/dnd-character/.meta/config.json
exercises/practice/dnd-character/.meta/tests.toml
exercises/practice/dnd-character/dub.sdl
exercises/practice/dnd-character/example/dnd_character.d
exercises/practice/dnd-character/source/dnd_character.d

Add dnd-character

---

config.json
exercises/practice/binary-search/.docs/instructions.md
exercises/practice/binary-search/.docs/introduction.md
exercises/practice/binary-search/.meta/config.json
exercises/practice/binary-search/.meta/tests.toml
exercises/practice/binary-search/dub.sdl
exercises/practice/binary-search/example/binary_search.d
exercises/practice/binary-search/source/binary_search.d

Add binary-search exercise

---

exercises/practice/dnd-character/source/dnd_character.d

Resolves an off-by-one bug introduced in #232.

Fix range checks in dnd-character

---

config.json
exercises/practice/robot-simulator/.docs/instructions.md
exercises/practice/robot-simulator/.meta/config.json
exercises/practice/robot-simulator/.meta/tests.toml
exercises/practice/robot-simulator/dub.sdl
exercises/practice/robot-simulator/example/robot_simulator.d
exercises/practice/robot-simulator/source/robot_simulator.d

Add robot-simulator

---

exercises/practice/collatz-conjecture/.meta/tests.toml
exercises/practice/collatz-conjecture/example/collatz_conjecture.d
exercises/practice/darts/.docs/instructions.md
exercises/practice/darts/.meta/config.json
exercises/practice/gigasecond/.meta/tests.toml
exercises/practice/gigasecond/source/gigasecond.d
exercises/practice/raindrops/.meta/config.json
exercises/practice/resistor-color-duo/.docs/instructions.md
exercises/practice/space-age/.docs/instructions.md
exercises/practice/space-age/.docs/introduction.md

Sync exercise docs and metadata

---

exercises/practice/zebra-puzzle/.docs/instructions.md
exercises/practice/zebra-puzzle/.docs/introduction.md
exercises/practice/zebra-puzzle/example/zebra_puzzle.d

Sync zebra-puzzle, now with hobbies

---

.github/workflows/tests.yml

We should be targeting specific compiler versions. I also added Windows to the matrix.

Update CI test matrix

---

config.json
exercises/practice/protein-translation/.docs/instructions.md
exercises/practice/protein-translation/.meta/config.json
exercises/practice/protein-translation/.meta/tests.toml
exercises/practice/protein-translation/dub.sdl
exercises/practice/protein-translation/example/protein_translation.d
exercises/practice/protein-translation/source/protein_translation.d

Add protein-translation

---

config.json
exercises/practice/secret-handshake/.docs/instructions.md
exercises/practice/secret-handshake/.docs/introduction.md
exercises/practice/secret-handshake/.meta/config.json
exercises/practice/secret-handshake/.meta/tests.toml
exercises/practice/secret-handshake/dub.sdl
exercises/practice/secret-handshake/example/secret_handshake.d
exercises/practice/secret-handshake/source/secret_handshake.d

add secret-handshake

---

config.json
exercises/practice/pig-latin/.docs/instructions.md
exercises/practice/pig-latin/.docs/introduction.md
exercises/practice/pig-latin/.meta/config.json
exercises/practice/pig-latin/.meta/tests.toml
exercises/practice/pig-latin/dub.sdl
exercises/practice/pig-latin/example/pig_latin.d
exercises/practice/pig-latin/source/pig_latin.d

Add pig-latin

---

config.json
exercises/practice/grade-school/.docs/instructions.md
exercises/practice/grade-school/.meta/config.json
exercises/practice/grade-school/.meta/tests.toml
exercises/practice/grade-school/dub.sdl
exercises/practice/grade-school/example/grade_school.d
exercises/practice/grade-school/source/grade_school.d

Add grade-school

---

exercises/practice/zebra-puzzle/example/zebra_puzzle.d
exercises/practice/zebra-puzzle/source/zebra_puzzle.d

ukranian => ukrainian

---

exercises/practice/armstrong-numbers/source/armstrong_numbers.d
exercises/practice/bob/source/bob.d
exercises/practice/collatz-conjecture/source/collatz_conjecture.d
exercises/practice/darts/source/darts.d
exercises/practice/etl/source/etl.d
exercises/practice/grains/source/grains.d

exercise stubs - part 1 of 4

---

exercises/practice/hamming/source/hamming.d
exercises/practice/isogram/source/isogram.d
exercises/practice/luhn/source/luhn.d
exercises/practice/matching-brackets/source/matching_brackets.d
exercises/practice/nth-prime/source/nth_prime.d
exercises/practice/pangram/source/pangram.d
exercises/practice/perfect-numbers/source/perfect_numbers.d
exercises/practice/prime-factors/source/prime_factors.d

exercise stubs - part 2 of 4

---

exercises/practice/raindrops/source/raindrops.d
exercises/practice/reverse-string/source/reverse_string.d
exercises/practice/rna-transcription/source/rna_transcription.d
exercises/practice/roman-numerals/source/roman_numerals.d

exercise stubs - part 3 of 4

---

bin/test-exercise
config.json
exercises/practice/two-bucket/.docs/instructions.md
exercises/practice/two-bucket/.meta/config.json
exercises/practice/two-bucket/.meta/tests.toml
exercises/practice/two-bucket/dub.sdl
exercises/practice/two-bucket/example/two_bucket.d
exercises/practice/two-bucket/source/two_bucket.d

plus cleaned up the bin/test-exercise script.

Add two-bucket exercise

---

exercises/practice/largest-series-product/.meta/tests.toml

Note that our D tests do not check error strings.
[no important files changed]

Sync largest-series-product tests

---

exercises/practice/bob/.meta/tests.toml
exercises/practice/bob/source/bob.d

The 'Multiple line question' test has been reimplemented.

Sync bob tests

---

exercises/practice/eliuds-eggs/.docs/introduction.md
exercises/practice/phone-number/.docs/instructions.md
exercises/practice/protein-translation/.docs/instructions.md

Sync exercise instructions

---

exercises/practice/intergalactic-transmission/.docs/instructions.md
exercises/practice/luhn/.docs/instructions.md
exercises/practice/reverse-string/.meta/tests.toml

sync exercises
